title: James O D Burton
logo: "images/image (1).png?raw=true"
description:
<br>
Over 2 years of hands-on experience in data analytics and visualization, backed by certifications in Python and SQL. Specialized focus on corporate finance.
<br>
Currently part of the prestigious leadership program at GE HealthCare, where I'm leveraging my data analytics skills in Python and SQL to drive financial decision-making.

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

