title: James O D Burton
logo: "images/image (1).png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  2+ years of data visualisation and manipulation experience with extensive finance experience. Master's degree in Finance & Investment from Loughborough University.
  <br><br>
  Currently working at GE HealthCare, in their well reknowned leadership program.  
  <br><br>
  <a href="https://www.linkedin.com/in/jod-burton/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://github.com/Jodburton">View My GitHub Profile</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
